# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-10 03:35
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeTai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msdt', models.CharField(max_length=255)),
                ('tendt', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HoiDong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahd', models.CharField(max_length=255)),
                ('ngaybv', models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 10, 3, 35, 45, 53716))),
                ('diachibv', models.CharField(max_length=255)),
                ('chutich', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gv_chutich', to=settings.AUTH_USER_MODEL)),
                ('msgv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gv_msgv', to=settings.AUTH_USER_MODEL)),
                ('thuky', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gv_thuky', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThongTin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_so', models.CharField(max_length=255, null=True)),
                ('ho_ten', models.CharField(max_length=255, null=True)),
                ('lop', models.CharField(max_length=255, null=True)),
                ('dia_chi', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=70, null=True)),
                ('sdt', models.IntegerField(default=0)),
                ('hoc_vi', models.CharField(max_length=255, null=True)),
                ('chuyen_nganh', models.CharField(max_length=255, null=True)),
                ('ngaysinh', models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 10, 3, 35, 45, 52599))),
                ('choice', models.CharField(choices=[('sv', 'Sinh Vien'), ('gv', 'Giang Vien')], max_length=45)),
                ('ma_detai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.DeTai')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_thongtin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
